// A small, hand-picked dictionary for the rule-based Easy Read Converter —
// deliberately not exhaustive. True plain-English rewriting needs
// understanding, not word substitution; this catches common jargon, and the
// "Ask an AI" panel exists precisely because this dictionary can't.
export const SIMPLE_WORD_MAP: Record<string, string> = {
  utilize: "use",
  utilise: "use",
  assistance: "help",
  require: "need",
  requires: "needs",
  required: "needed",
  communicate: "talk",
  individual: "person",
  individuals: "people",
  approximately: "about",
  commence: "start",
  commenced: "started",
  terminate: "end",
  terminated: "ended",
  sufficient: "enough",
  obtain: "get",
  obtained: "got",
  purchase: "buy",
  purchased: "bought",
  residence: "home",
  physician: "doctor",
  regarding: "about",
  additional: "more",
  numerous: "many",
  facilitate: "help",
  demonstrate: "show",
  demonstrates: "shows",
  inquire: "ask",
  inform: "tell",
  informed: "told",
  provide: "give",
  provides: "gives",
  provided: "gave",
  participate: "take part",
  participation: "taking part",
  immediately: "now",
  frequently: "often",
  attempt: "try",
  attempted: "tried",
  endeavour: "try",
  endeavor: "try",
  prior: "before",
  subsequent: "after",
  currently: "now",
  therefore: "so",
  however: "but",
  nevertheless: "still",
  accommodate: "help",
  accommodation: "housing",
  transportation: "transport",
  utilisation: "use",
  utilization: "use",
};

export interface KeywordEmoji {
  keyword: string;
  emoji: string;
}

export const KEYWORD_EMOJI_MAP: KeywordEmoji[] = [
  { keyword: "doctor", emoji: "🩺" },
  { keyword: "hospital", emoji: "🏥" },
  { keyword: "medicine", emoji: "💊" },
  { keyword: "medication", emoji: "💊" },
  { keyword: "appointment", emoji: "📅" },
  { keyword: "home", emoji: "🏠" },
  { keyword: "house", emoji: "🏠" },
  { keyword: "money", emoji: "💰" },
  { keyword: "pay", emoji: "💰" },
  { keyword: "food", emoji: "🍽️" },
  { keyword: "eat", emoji: "🍽️" },
  { keyword: "water", emoji: "💧" },
  { keyword: "drink", emoji: "🥤" },
  { keyword: "sleep", emoji: "😴" },
  { keyword: "bed", emoji: "🛏️" },
  { keyword: "school", emoji: "🏫" },
  { keyword: "work", emoji: "💼" },
  { keyword: "job", emoji: "💼" },
  { keyword: "family", emoji: "👨‍👩‍👧‍👦" },
  { keyword: "friend", emoji: "🧑‍🤝‍🧑" },
  { keyword: "phone", emoji: "📞" },
  { keyword: "call", emoji: "📞" },
  { keyword: "email", emoji: "✉️" },
  { keyword: "important", emoji: "❗" },
  { keyword: "safe", emoji: "✅" },
  { keyword: "safety", emoji: "✅" },
  { keyword: "danger", emoji: "⚠️" },
  { keyword: "dangerous", emoji: "⚠️" },
  { keyword: "help", emoji: "🤝" },
  { keyword: "bus", emoji: "🚌" },
  { keyword: "car", emoji: "🚗" },
  { keyword: "travel", emoji: "🧳" },
  { keyword: "time", emoji: "⏰" },
  { keyword: "date", emoji: "📅" },
  { keyword: "meeting", emoji: "🗂️" },
  { keyword: "support", emoji: "🤝" },
  { keyword: "worker", emoji: "🧑‍🔧" },
  { keyword: "shower", emoji: "🚿" },
  { keyword: "bathroom", emoji: "🚻" },
  { keyword: "clean", emoji: "🧼" },
  { keyword: "clothes", emoji: "👕" },
  { keyword: "emergency", emoji: "🆘" },
  { keyword: "please", emoji: "🙏" },
  { keyword: "thank", emoji: "🙏" },
  { keyword: "yes", emoji: "✅" },
  { keyword: "no", emoji: "❌" },
];
