import Link from "next/link";

export const metadata = {
  title: "Disclaimer — Toolkit",
};

export default function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-10 sm:py-14">
      <h1 className="font-display text-3xl font-bold mb-2">Disclaimer</h1>
      <p className="text-muted mb-8">Last updated: [add date before publishing]</p>

      <div className="space-y-6 [&_h2]:font-display [&_h2]:text-xl [&_h2]:font-bold [&_h2]:mb-2 [&_p]:mb-3">
        <section>
          <h2>These tools are not medical advice</h2>
          <p>
            Everything on this site is intended to help with everyday
            communication, routines, learning, organisation and
            self-expression. It is <strong>not</strong> medical, clinical,
            therapeutic, psychological, behavioural, legal or financial
            advice, and it is not a diagnosis, treatment or care plan for
            any person or condition.
          </p>
          <p>
            No tool on this site — including the Communication Board,
            Behaviour Tracking Tool, Social Story Creator, Emotion Tracker,
            or any other current or future tool — is a substitute for
            assessment, advice or care from a qualified, registered
            professional who knows the person involved.
          </p>
        </section>

        <section>
          <h2>Please seek professional advice</h2>
          <p>
            If you have any concern about a person&apos;s health, development,
            behaviour, pain, safety, mental health, or wellbeing, please
            seek advice from an appropriately qualified professional, such
            as:
          </p>
          <ul className="mb-3 list-disc pl-6 space-y-1">
            <li>Their GP or another medical doctor</li>
            <li>A psychologist, psychiatrist, or mental health clinician</li>
            <li>An occupational therapist, speech pathologist, physiotherapist, or behaviour support practitioner</li>
            <li>Their NDIS support coordinator or treating team</li>
            <li>Another relevant registered health professional</li>
          </ul>
          <p>
            Information logged in tools like the Behaviour Tracking Tool can
            be a useful thing to bring to a conversation with one of these
            professionals — it isn&apos;t a replacement for that
            conversation.
          </p>
        </section>

        <section>
          <h2>In an emergency</h2>
          <p>
            If someone is in immediate danger, seriously unwell, or their
            life may be at risk, call <strong>000</strong> (Australia) or go
            to your nearest emergency department right away. Don&apos;t wait
            to use one of these tools first.
          </p>
          <p>For urgent mental health support:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Lifeline — 13 11 14 (24/7)</li>
            <li>Kids Helpline (ages 5–25) — 1800 55 1800 (24/7)</li>
            <li>13YARN, for Aboriginal and Torres Strait Islander peoples — 13 92 76 (24/7)</li>
          </ul>
        </section>

        <section>
          <h2>No professional relationship is created</h2>
          <p>
            Using this site does not create a doctor-patient, therapist-
            client, or any other professional relationship between you and
            [Organisation legal name] or its contributors. We are not
            responsible for decisions made based on information entered
            into, or generated by, these tools.
          </p>
        </section>
      </div>

      <p className="mt-10 text-sm text-muted">
        <Link href="/" className="font-semibold text-brand hover:underline">
          ← Back home
        </Link>
      </p>
    </div>
  );
}
